# Generated by Django 5.2.5 on 2025-08-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
